# Generated by Django 5.2.5 on 2025-08-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_activated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_activated',
            new_name='has_activated',
        ),
    ]
