# Generated by Django 5.2.5 on 2025-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active (In Stock)'), ('inactive', 'Out of Stock')], max_length=100),
        ),
    ]
