# Generated by Django 5.2.5 on 2025-08-12 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_worker_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.worker'),
        ),
    ]
