# Generated by Django 5.2.5 on 2025-08-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_activateaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, choices=[('Receptionist', 'Receptionist'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
