# Generated by Django 5.2.5 on 2025-08-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_worker_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_live', models.BooleanField(default=False)),
                ('always_live', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'POS Configuration',
                'verbose_name_plural': 'POS Configuration',
            },
        ),
        migrations.AlterField(
            model_name='activateaccount',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, choices=[('Sales', 'Sales Personnel'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
