# Generated by Django 5.2.5 on 2025-08-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='id_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='id_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
