# Generated by Django 5.2.5 on 2025-08-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='alway_live',
            field=models.BooleanField(default=False),
        ),
    ]
