# Generated by Django 5.2.5 on 2025-08-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_pos_alway_live'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pos',
            options={'verbose_name': 'POS Configuration', 'verbose_name_plural': 'POS Configuration'},
        ),
        migrations.RenameField(
            model_name='pos',
            old_name='alway_live',
            new_name='always_live',
        ),
    ]
